var com = {
	"qmino":{
		"miredot":{
		},
	},
};
com.qmino.miredot.restApiSource = {
	"projectName":"store",
	"projectVersion":"0.0.1-SNAPSHOT",
	"projectTitle":"Wingify Online Store",
	"buildSystem":"maven 3",
	"miredotVersion":"2.0.3",
	"miredotRevision":"22d2e7a3171a+",
	"jsonDocEnabled":true,
	"jsonDocHidden":false,
	"singlePage":false,
	"hideLogoOnTop":false,
	"dateOfGeneration":"2017-05-14 21:00:02",
	"validLicense":true,
	"licenseErrorMessage":[
		"Build is approved",

	],
	"onlineLicense":true,
	"loginUrl":null,
	"licenseType":"PRO",
	"allowUsageTracking":false,
	"baseUrl":"https://wingifystore.herokuapp.com/wingify",
	"applicationPath":"",
	"issuesTabHidden":false,
};

com.qmino.miredot.restApiSource.tos = {
	"org_shubham_wingify_store_model_Product_in":{
		"type":"complex",
		"name":"org_shubham_wingify_store_model_Product_in",
		"content":[
		],
	},
	"org_shubham_wingify_store_model_Product_out":{
		"type":"complex",
		"name":"org_shubham_wingify_store_model_Product_out",
		"content":[
		],
	},
	"javax_ws_rs_core_MediaType_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_MediaType_in",
		"content":[
		],
	},
	"javax_ws_rs_core_MediaType_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_MediaType_out",
		"content":[
		],
	},
	"javax_ws_rs_core_Response_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_Response_in",
		"content":[
		],
	},
	"javax_ws_rs_core_Response_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_Response_out",
		"content":[
		],
	},
	"javax_ws_rs_core_PathSegment_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_PathSegment_in",
		"content":[
		],
	},
	"javax_ws_rs_core_PathSegment_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_PathSegment_out",
		"content":[
		],
	},
	"javax_ws_rs_core_UriBuilder_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_UriBuilder_in",
		"content":[
		],
	},
	"javax_ws_rs_core_UriBuilder_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_UriBuilder_out",
		"content":[
		],
	},
	"javax_ws_rs_core_UriInfo_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_UriInfo_in",
		"content":[
		],
	},
	"javax_ws_rs_core_UriInfo_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_UriInfo_out",
		"content":[
		],
	},
	"javax_ws_rs_core_NewCookie_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_NewCookie_in",
		"content":[
		],
	},
	"javax_ws_rs_core_NewCookie_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_NewCookie_out",
		"content":[
		],
	},
	"javax_ws_rs_core_EntityTag_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_EntityTag_in",
		"content":[
		],
	},
	"javax_ws_rs_core_EntityTag_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_EntityTag_out",
		"content":[
		],
	},
	"javax_ws_rs_core_Response$StatusType_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_Response$StatusType_in",
		"content":[
		],
	},
	"javax_ws_rs_core_Response$StatusType_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_Response$StatusType_out",
		"content":[
		],
	},
	"javax_ws_rs_core_Link_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_Link_in",
		"content":[
		],
	},
	"javax_ws_rs_core_Link_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_Link_out",
		"content":[
		],
	},
};
com.qmino.miredot.restApiSource.enums = {
	"javax_ws_rs_core_Response$Status$Family":{
		"type":"enum",
		"name":"javax.ws.rs.core.Response$Status$Family",
		"values":[
			{
				"name":"INFORMATIONAL",
				"comment":null,
			},
			{
				"name":"SUCCESSFUL",
				"comment":null,
			},
			{
				"name":"REDIRECTION",
				"comment":null,
			},
			{
				"name":"CLIENT_ERROR",
				"comment":null,
			},
			{
				"name":"SERVER_ERROR",
				"comment":null,
			},
			{
				"name":"OTHER",
				"comment":null,
			},
		],
	},
};
com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_in"].content = [
	{
		"name":"name",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"description",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"price",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"addedOn",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"date string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"id",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_in"].comment = null;
com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_out"].content = [
	{
		"name":"name",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"id",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"description",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"price",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"addedOn",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"date string",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_out"].content = [
	{
		"name":"type",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"parameters",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"wildcardType",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"subtype",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"wildcardSubtype",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"].content = [
	{
		"name":"length",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"language",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"java.util.Locale",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"location",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"java.net.URI",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"lastModified",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"date string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"headers",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"collection",
				"typeValue":{
					"type":"simple",
					"typeValue":"object",
				},
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"date",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"date string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"status",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"cookies",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_out"],
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"entity",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"object",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"mediaType",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"entityTag",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"stringHeaders",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"collection",
				"typeValue":{
					"type":"simple",
					"typeValue":"string",
				},
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"statusInfo",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"allowedMethods",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"metadata",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"collection",
				"typeValue":{
					"type":"simple",
					"typeValue":"object",
				},
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"links",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_out"],
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_PathSegment_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_PathSegment_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_PathSegment_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_PathSegment_out"].content = [
	{
		"name":"path",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"matrixParameters",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"collection",
				"typeValue":{
					"type":"simple",
					"typeValue":"string",
				},
			},
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_PathSegment_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_PathSegment_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriInfo_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriInfo_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriInfo_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriInfo_out"].content = [
	{
		"name":"absolutePath",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"java.net.URI",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"path",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"queryParameters",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"collection",
				"typeValue":{
					"type":"simple",
					"typeValue":"string",
				},
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"baseUri",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"java.net.URI",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"matchedURIs",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"pathSegments",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_PathSegment_out"],
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"requestUri",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"java.net.URI",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"absolutePathBuilder",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"pathParameters",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"collection",
				"typeValue":{
					"type":"simple",
					"typeValue":"string",
				},
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"matchedResources",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":{
				"type":"simple",
				"typeValue":"object",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"requestUriBuilder",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"baseUriBuilder",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"],
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriInfo_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriInfo_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_out"].content = [
	{
		"name":"name",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"value",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"path",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"domain",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"version",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"comment",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"secure",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"maxAge",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"httpOnly",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"expiry",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"date string",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_out"].content = [
	{
		"name":"value",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"weak",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_out"].content = [
	{
		"name":"family",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.enums["javax_ws_rs_core_Response$Status$Family"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"statusCode",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"reasonPhrase",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_out"].content = [
	{
		"name":"type",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"params",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"title",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"rel",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"uriBuilder",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"rels",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"uri",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"java.net.URI",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_out"].comment = null;
com.qmino.miredot.restApiSource.interfaces = [
	{
		"beschrijving":"",
		"url":"/products/{productId}",
		"http":"PUT",
		"title":null,
		"tags":[
			
		],
		"authors":[
			"Shubham Shrivastav",

		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
			"application/json",
			"text/xml",
		],
		"produces":[
			"application/json",
			"text/xml",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_out"],
			"comment":null,
		},
		"statusCodes":[
			{
				"httpCode":200,
				"comment":"The service call has completed successfully.",
			},
			{
				"httpCode":412,
				"comment":"Invalid JSON/XML input.",
			},
			{
				"httpCode":500,
				"comment":"The service call has not succeeded.",
			},
		],
		"hash":"1240924293",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"productId",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
				{
					"typeValue":com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_in"],
					"comment":null,
					"jaxrs":"BODY",
				},
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/products/{productId}",
		"http":"DELETE",
		"title":null,
		"tags":[
			
		],
		"authors":[
			"Shubham Shrivastav",

		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
			"text/xml",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
		},
		"statusCodes":[
			{
				"httpCode":200,
				"comment":"The service call has completed successfully.",
			},
			{
				"httpCode":500,
				"comment":"The service call has not succeeded.",
			},
		],
		"hash":"610554705",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"productId",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/products/{productId}",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			"Shubham Shrivastav",

		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
			"text/xml",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_out"],
			"comment":null,
		},
		"statusCodes":[
			{
				"httpCode":200,
				"comment":"The service call has completed successfully.",
			},
			{
				"httpCode":500,
				"comment":"The service call has not succeeded.",
			},
		],
		"hash":"387222786",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"productId",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/products/",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			"Shubham Shrivastav",

		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
			"text/xml",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":{
				"type":"collection",
				"typeValue":com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_out"],
			},
			"comment":null,
		},
		"statusCodes":[
			{
				"httpCode":200,
				"comment":"The service call has completed successfully.",
			},
			{
				"httpCode":500,
				"comment":"The service call has not succeeded.",
			},
		],
		"hash":"-1959081325",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
				{
					"name":"year",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"QUERY",
				},
				{
					"name":"start",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"QUERY",
				},
				{
					"name":"limit",
					"typeValue":{
						"type":"simple",
						"typeValue":"number",
					},
					"comment":null,
					"jaxrs":"QUERY",
				},
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/products/",
		"http":"POST",
		"title":null,
		"tags":[
			
		],
		"authors":[
			"Shubham Shrivastav",

		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
			"application/json",
			"text/xml",
		],
		"produces":[
			"application/json",
			"text/xml",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
			{
				"httpCode":200,
				"comment":"The service call has completed successfully.",
			},
			{
				"httpCode":412,
				"comment":"Invalid JSON/XML input.",
			},
			{
				"httpCode":500,
				"comment":"The service call has not succeeded.",
			},
		],
		"hash":"1678203227",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
				{
					"typeValue":com.qmino.miredot.restApiSource.tos["org_shubham_wingify_store_model_Product_in"],
					"comment":null,
					"jaxrs":"BODY",
				},
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
];
com.qmino.miredot.projectWarnings = [
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1240924293",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"updateProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1240924293",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"updateProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1240924293",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"updateProduct",
		"entity":"productId",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1240924293",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"updateProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1240924293",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"updateProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"610554705",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"removeProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"610554705",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"removeProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"610554705",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"removeProduct",
		"entity":"productId",
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"387222786",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"getProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"387222786",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"getProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"387222786",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"getProduct",
		"entity":"productId",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"387222786",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"getProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"-1959081325",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"getAllProducts",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"-1959081325",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"getAllProducts",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"-1959081325",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"getAllProducts",
		"entity":"year",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"-1959081325",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"getAllProducts",
		"entity":"start",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"-1959081325",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"getAllProducts",
		"entity":"limit",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"-1959081325",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"getAllProducts",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1678203227",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"addProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1678203227",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"addProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1678203227",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"addProduct",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1678203227",
		"implementationClass":"org.shubham.wingify.store.resource.ProductResource",
		"implementationMethod":"addProduct",
		"entity":null,
	},
];
com.qmino.miredot.processErrors = [
];
var customHttpMethods = [
];

